In [1]:
pip install tensorflow

In [5]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [7]:
a=tf.constant(10);
print(a)

tf.Tensor(10, shape=(), dtype=int32)


In [10]:
v=tf.constant([1,2,3,4])
print(v)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [12]:
m=tf.constant([[1,2],[3,4]])
print(m)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [13]:
a=tf.constant([10,20,30])
b=tf.constant([50,60,70])
print(a+b)

tf.Tensor([ 60  80 100], shape=(3,), dtype=int32)


In [16]:
v = tf.constant([1,2,3,4])
u= tf.constant([5,6,7,8])
print(v)
print(u)

print("Add :",tf.add(v,u))
print("subtract : ",tf.subtract(v,u))
print("multiply : ",tf.multiply(v,u))
print("divide : ",tf.divide(v,u))
print("floordiv : ",tf.math.floordiv(v,u))
print("power : ",tf.pow(v,u))

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
Add : tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
subtract :  tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
multiply :  tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
divide :  tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)
floordiv :  tf.Tensor([0 0 0 0], shape=(4,), dtype=int32)
power :  tf.Tensor([    1    64  2187 65536], shape=(4,), dtype=int32)


In [14]:
a = tf.constant([10, 20, 20])
print(a.dtype, a.shape, tf.rank(a))

<dtype: 'int32'> (3,) tf.Tensor(1, shape=(), dtype=int32)


In [15]:
import numpy as np
np_array = np.array([[1,2,3], [4,5,6]])

tensor = tf.convert_to_tensor(np_array)
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int64)
